[book]
authors = ["Alexander Jophus"]
language = "en"
multilingual = false
src = "src"

[output.markdown]
[output.html]
edit-url-template = "https://github.com/alexanderjophus/sl/edit/main/docs/{path}"
search.use-boolean-and = true